package uk.ac.manchester.dstoolkit.service.impl.morphisms.schematiccorrespondence;

import static org.junit.Assert.*;

import org.junit.Before;
import org.junit.Test;


public class GenerateSchematicCorrespondencesForPhenotypeServiceImplTestGenerateMissingSuperLexicalSchematicCorrespondenceBetweenSuperLexicalAndSuperAbstractWithoutEquivalentSuperLexical {

	@Before
	public void setUp() throws Exception {
	}

	@Test
	public void testGenerateMissingSuperLexicalSchematicCorrespondenceBetweenSuperLexicalAndSuperAbstractWithoutEquivalentSuperLexical() {
		fail("Not yet implemented");
	}

}
