package uk.ac.manchester.dstoolkit.service.impl.morphisms.schematiccorrespondence;

import static org.junit.Assert.*;

import org.junit.Before;
import org.junit.Test;


public class GenerateSchematicCorrespondencesForPhenotypeServiceImplTestGenerateSameNameOrDifferentNameSameConstructSchematicCorrespondenceBetweenTwoCanonicalModelConstructs {

	@Before
	public void setUp() throws Exception {
	}

	@Test
	public void testGenerateSameNameOrDifferentNameSameConstructSchematicCorrespondenceBetweenTwoCanonicalModelConstructs() {
		fail("Not yet implemented");
	}

}
