//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 04:59:33 PM BRT 
//


package uk.ac.manchester.dstoolkit.service.impl.util.importexport.RDFModel;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.ac.manchester.dstoolkit.service.impl.util.importexport.RDFModel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.ac.manchester.dstoolkit.service.impl.util.importexport.RDFModel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RDFClass }
     * 
     */
    public RDFClass createRDFClass() {
        return new RDFClass();
    }

    /**
     * Create an instance of {@link RDFModel }
     * 
     */
    public RDFModel createRDFModel() {
        return new RDFModel();
    }

    /**
     * Create an instance of {@link RDFPredicate }
     * 
     */
    public RDFPredicate createRDFPredicate() {
        return new RDFPredicate();
    }

    /**
     * Create an instance of {@link RDFBlankNode }
     * 
     */
    public RDFBlankNode createRDFBlankNode() {
        return new RDFBlankNode();
    }

    /**
     * Create an instance of {@link RDFProperty }
     * 
     */
    public RDFProperty createRDFProperty() {
        return new RDFProperty();
    }

}
