package uk.ac.manchester.dstoolkit.domain.provenance;

/**
 * @author chedeler
 * @author klitos
 */
public enum ControlParameterType {
	PRECISION_THRESHOLD, RECALL_THRESHOLD,

	MAX_NUMBER_OF_QUERY_RESULTS, QUERY_FETCH_SIZE,

	MATCH_SCORE_THRESHOLD, ALIGNMENT_THRESHOLD,
	
	DO_NOT_AGGREGATE, EXPERIMENT,

	MATCH_SELECT_DIRECTION_TYPE,

	MATCH_SELECT_SELECTION_TYPE, MATCH_SELECT_MAXN_CANDIDATE_NUMBER, MATCH_SELECT_MAXDELTA_DELTA, MATCH_SELECT_THRESHOLD_VALUE,

	MATCH_AGGREGATE_AGGREGATION_TYPE, MATCH_AGGREGATE_SIMWEIGHT_WEIGHT1, MATCH_AGGREGATE_SIMWEIGHT_WEIGHT2, MATCH_AGGREGATE_SIMWEIGHT_WEIGHT3, MATCH_AGGREGATE_SIMWEIGHT_WEIGHT4, MATCH_AGGREGATE_SIMWEIGHT_WEIGHT5,

	MATCH_AGGREGATE_SIMWEIGHT_WEIGHT6, MATCH_AGGREGATE_SIMWEIGHT_WEIGHT7, MATCH_AGGREGATE_SIMWEIGHT_WEIGHT8, MATCH_AGGREGATE_SIMWEIGHT_WEIGHT9, MATCH_AGGREGATE_SIMWEIGHT_WEIGHT10,

	INFERCORR_POPULATION_SIZE, INFERCORR_CROSSOVER_RATE, INFERCORR_MUTATION_RATE, INFERCORR_NUMBER_OF_GENERATIONS, INFERCORR_GENOME_SIZE,

	//TODO: check the following parameters in code and see how they map to parameters in ecj
	INFERCORR_CROSSOVER_OP_INDEX, INFERCORR_MUTATION_OP_INDEX, INFERCORR_PARENT_SELECTION_OP_INDEX,

	INFERCORR_SURVIVOR_SELECTION_OP_INDEX, INFERCORR_SURVIVORS_SELECT_OFFSPRING_SIZE, INFERCORR_BEST_PARENT_RATE,
	
	//SemanticMatrices Control Parameters
	USE_REASONER, DO_CONFLICT_RESOLUTION,
	
	//Control Parameters for calculating the error and the % of change
	ONLY_SYN_SEM_CELLS, ALL_SYN_SEM_CELLS, SHOW_PERC_INCR_DECR, SHOW_PERC_CHANGE, PLOT_PERC_INCR_DECR, PLOT_PERC_CHANGE,
	
	BAYESIAN_APPROACH, MATCH_RANKING, RANKING_DESC, RANKING_ASCE,
	
	SYNTACTIC_EVIDENCE_ASSIMILATION, PLOT_TYPE, DAMPENING_EFFECT_POLICY, ERROR_MEASURE_TYPE;

	//(float) INFERCORR_BEST_PARENT_RATE, if the survivors selection use BestParents_BestOffspring, this para decides the proportion of best parents into the next generation
}
