/**
 * 
 */
package uk.ac.manchester.dstoolkit.service.impl.morphisms.schematiccorrespondence.util;

import static org.junit.Assert.*;

import org.junit.Before;
import org.junit.Test;


/**
 * @author chedeler
 *
 */
public class DerivedOneToOneMatchingsGeneratorServiceImplTestProcessMatchingAndPlaceInMatchedSourceConstructsTargetConstructsMatchingsMap {

	/**
	 * @throws java.lang.Exception
	 */
	@Before
	public void setUp() throws Exception {
	}

	/**
	 * Test method for {@link uk.ac.manchester.dstoolkit.service.impl.morphisms.schematiccorrespondence.util.DerivedOneToOneMatchingsGeneratorServiceImpl#processMatchingAndPlaceInMatchedSourceConstructsTargetConstructsMatchingsMap(java.util.Map, java.util.Set, java.util.Set, uk.ac.manchester.dstoolkit.domain.models.morphisms.matching.OneToOneMatching)}.
	 */
	@Test
	public void testProcessMatchingAndPlaceInMatchedSourceConstructsTargetConstructsMatchingsMap() {
		fail("Not yet implemented");
	}

}
