package uk.ac.manchester.dstoolkit.service.impl.morphisms.schematiccorrespondence.util;

import static org.junit.Assert.*;

import org.junit.Before;
import org.junit.Test;


public class DerivedOneToOneMatchingsGeneratorServiceImplTestAddToTargetSuperLexicalSourceSuperLexicalsDerivedOneToOneMatchingMap {

	@Before
	public void setUp() throws Exception {
	}

	@Test
	public void testAddToTargetSuperLexicalSourceSuperLexicalsDerivedOneToOneMatchingMap() {
		fail("Not yet implemented");
	}

}
