//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 04:59:33 PM BRT 
//


package uk.ac.manchester.dstoolkit.service.impl.util.importexport.RDFSchema;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.ac.manchester.dstoolkit.service.impl.util.importexport.RDFSchema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.ac.manchester.dstoolkit.service.impl.util.importexport.RDFSchema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RDFWeakEntityType }
     * 
     */
    public RDFWeakEntityType createRDFWeakEntityType() {
        return new RDFWeakEntityType();
    }

    /**
     * Create an instance of {@link RDFEntityTypes }
     * 
     */
    public RDFEntityTypes createRDFEntityTypes() {
        return new RDFEntityTypes();
    }

    /**
     * Create an instance of {@link RDFBinaryRelationshipType }
     * 
     */
    public RDFBinaryRelationshipType createRDFBinaryRelationshipType() {
        return new RDFBinaryRelationshipType();
    }

    /**
     * Create an instance of {@link MultiAttrOfRDFEntityType }
     * 
     */
    public MultiAttrOfRDFEntityType createMultiAttrOfRDFEntityType() {
        return new MultiAttrOfRDFEntityType();
    }

    /**
     * Create an instance of {@link RDFEntityType }
     * 
     */
    public RDFEntityType createRDFEntityType() {
        return new RDFEntityType();
    }

    /**
     * Create an instance of {@link RDFIdentifiedRelationshipType }
     * 
     */
    public RDFIdentifiedRelationshipType createRDFIdentifiedRelationshipType() {
        return new RDFIdentifiedRelationshipType();
    }

    /**
     * Create an instance of {@link SimpleAttrOfRDFWeakEntityType }
     * 
     */
    public SimpleAttrOfRDFWeakEntityType createSimpleAttrOfRDFWeakEntityType() {
        return new SimpleAttrOfRDFWeakEntityType();
    }

    /**
     * Create an instance of {@link RDFSchemaMetadata }
     * 
     */
    public RDFSchemaMetadata createRDFSchemaMetadata() {
        return new RDFSchemaMetadata();
    }

    /**
     * Create an instance of {@link CompositeAttrOfRDFEntityType }
     * 
     */
    public CompositeAttrOfRDFEntityType createCompositeAttrOfRDFEntityType() {
        return new CompositeAttrOfRDFEntityType();
    }

    /**
     * Create an instance of {@link SimpleAttrOfRDFEntityType }
     * 
     */
    public SimpleAttrOfRDFEntityType createSimpleAttrOfRDFEntityType() {
        return new SimpleAttrOfRDFEntityType();
    }

}
