//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 04:59:33 PM BRT 
//


package uk.ac.manchester.dstoolkit.service.impl.util.importexport.RDFSchema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RDFRelationshipName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FromRDFEntityType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ToRDFEntityType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CardinalityRatio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="namespace" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rdfRelationshipName",
    "fromRDFEntityType",
    "toRDFEntityType",
    "cardinalityRatio"
})
@XmlRootElement(name = "RDFIdentifiedRelationshipType")
public class RDFIdentifiedRelationshipType {

    @XmlElement(name = "RDFRelationshipName", required = true)
    protected String rdfRelationshipName;
    @XmlElement(name = "FromRDFEntityType")
    protected String fromRDFEntityType;
    @XmlElement(name = "ToRDFEntityType")
    protected String toRDFEntityType;
    @XmlElement(name = "CardinalityRatio")
    protected String cardinalityRatio;
    @XmlAttribute
    protected String namespace;

    /**
     * Gets the value of the rdfRelationshipName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRDFRelationshipName() {
        return rdfRelationshipName;
    }

    /**
     * Sets the value of the rdfRelationshipName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRDFRelationshipName(String value) {
        this.rdfRelationshipName = value;
    }

    /**
     * Gets the value of the fromRDFEntityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromRDFEntityType() {
        return fromRDFEntityType;
    }

    /**
     * Sets the value of the fromRDFEntityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromRDFEntityType(String value) {
        this.fromRDFEntityType = value;
    }

    /**
     * Gets the value of the toRDFEntityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToRDFEntityType() {
        return toRDFEntityType;
    }

    /**
     * Sets the value of the toRDFEntityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToRDFEntityType(String value) {
        this.toRDFEntityType = value;
    }

    /**
     * Gets the value of the cardinalityRatio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardinalityRatio() {
        return cardinalityRatio;
    }

    /**
     * Sets the value of the cardinalityRatio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardinalityRatio(String value) {
        this.cardinalityRatio = value;
    }

    /**
     * Gets the value of the namespace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamespace() {
        return namespace;
    }

    /**
     * Sets the value of the namespace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamespace(String value) {
        this.namespace = value;
    }

}
