//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 04:59:33 PM BRT 
//


package uk.ac.manchester.dstoolkit.service.impl.util.importexport.RDFSchema;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RDFWeakEntityTypeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}SimpleAttrOfRDFWeakEntityType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MultiAttrOfRDFWeakEntityType" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}RDFIdentifiedRelationshipType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="rdftype" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rdfWeakEntityTypeName",
    "simpleAttrOfRDFWeakEntityType",
    "multiAttrOfRDFWeakEntityType",
    "rdfIdentifiedRelationshipType"
})
@XmlRootElement(name = "RDFWeakEntityType")
public class RDFWeakEntityType {

    @XmlElement(name = "RDFWeakEntityTypeName", required = true)
    protected String rdfWeakEntityTypeName;
    @XmlElement(name = "SimpleAttrOfRDFWeakEntityType")
    protected List<SimpleAttrOfRDFWeakEntityType> simpleAttrOfRDFWeakEntityType;
    @XmlElement(name = "MultiAttrOfRDFWeakEntityType")
    protected List<String> multiAttrOfRDFWeakEntityType;
    @XmlElement(name = "RDFIdentifiedRelationshipType")
    protected List<RDFIdentifiedRelationshipType> rdfIdentifiedRelationshipType;
    @XmlAttribute
    @XmlSchemaType(name = "anyURI")
    protected String rdftype;

    /**
     * Gets the value of the rdfWeakEntityTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRDFWeakEntityTypeName() {
        return rdfWeakEntityTypeName;
    }

    /**
     * Sets the value of the rdfWeakEntityTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRDFWeakEntityTypeName(String value) {
        this.rdfWeakEntityTypeName = value;
    }

    /**
     * Gets the value of the simpleAttrOfRDFWeakEntityType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the simpleAttrOfRDFWeakEntityType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSimpleAttrOfRDFWeakEntityType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimpleAttrOfRDFWeakEntityType }
     * 
     * 
     */
    public List<SimpleAttrOfRDFWeakEntityType> getSimpleAttrOfRDFWeakEntityType() {
        if (simpleAttrOfRDFWeakEntityType == null) {
            simpleAttrOfRDFWeakEntityType = new ArrayList<SimpleAttrOfRDFWeakEntityType>();
        }
        return this.simpleAttrOfRDFWeakEntityType;
    }

    /**
     * Gets the value of the multiAttrOfRDFWeakEntityType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the multiAttrOfRDFWeakEntityType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMultiAttrOfRDFWeakEntityType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getMultiAttrOfRDFWeakEntityType() {
        if (multiAttrOfRDFWeakEntityType == null) {
            multiAttrOfRDFWeakEntityType = new ArrayList<String>();
        }
        return this.multiAttrOfRDFWeakEntityType;
    }

    /**
     * Gets the value of the rdfIdentifiedRelationshipType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rdfIdentifiedRelationshipType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRDFIdentifiedRelationshipType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RDFIdentifiedRelationshipType }
     * 
     * 
     */
    public List<RDFIdentifiedRelationshipType> getRDFIdentifiedRelationshipType() {
        if (rdfIdentifiedRelationshipType == null) {
            rdfIdentifiedRelationshipType = new ArrayList<RDFIdentifiedRelationshipType>();
        }
        return this.rdfIdentifiedRelationshipType;
    }

    /**
     * Gets the value of the rdftype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRdftype() {
        return rdftype;
    }

    /**
     * Sets the value of the rdftype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRdftype(String value) {
        this.rdftype = value;
    }

}
