package uk.ac.manchester.dstoolkit.service.impl.morphisms.schematiccorrespondence.representation.entitylevelrelationship;

import static org.junit.Assert.fail;

import java.util.List;

import org.junit.Before;
import org.junit.Test;

import uk.ac.manchester.dstoolkit.service.impl.morphisms.schematiccorrespondence.representation.vectorspacemodel.VectorSpaceVector;

public class ELREntityLevelRelationshipIntegrationTestCalculateCosineSimilarityOfSourceAndTargetVectorCombinationsAndIdentifyCombinationWithHighestSimilarity {

	private ELREntityLevelRelationship elrEntityLevelRelationship;
	private List<VectorSpaceVector> sourceVectors;
	private List<VectorSpaceVector> targetVectors;

	@Before
	public void setUp() throws Exception {
	}

	@Test
	public void testCalculateCosineSimilarityOfSourceAndTargetVectorCombinationsAndIdentifyCombinationWithHighestSimilarity() {
		fail("Not yet implemented");
	}

}
