//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 04:59:32 PM BRT 
//


package uk.ac.manchester.dstoolkit.service.impl.util.importexport.schemaelementstoexclude;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}name"/>
 *         &lt;element ref="{}ElementsToExclude"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "elementsToExclude"
})
@XmlRootElement(name = "Schema")
public class Schema {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(name = "ElementsToExclude", required = true)
    protected ElementsToExclude elementsToExclude;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the elementsToExclude property.
     * 
     * @return
     *     possible object is
     *     {@link ElementsToExclude }
     *     
     */
    public ElementsToExclude getElementsToExclude() {
        return elementsToExclude;
    }

    /**
     * Sets the value of the elementsToExclude property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementsToExclude }
     *     
     */
    public void setElementsToExclude(ElementsToExclude value) {
        this.elementsToExclude = value;
    }

}
