//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 04:59:33 PM BRT 
//


package uk.ac.manchester.dstoolkit.service.impl.util.importexport.ExpMatrix;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="class1URI" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="class2URI" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="evidence" type="{}varList" minOccurs="0"/>
 *         &lt;element name="score" type="{}scoreType" minOccurs="0"/>
 *         &lt;element name="rangeName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rangeMIN" type="{}scoreType" minOccurs="0"/>
 *         &lt;element name="rangeMAX" type="{}scoreType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "class1URI",
    "class2URI",
    "evidence",
    "score",
    "rangeName",
    "rangeMIN",
    "rangeMAX"
})
@XmlRootElement(name = "ClassesAlign")
public class ClassesAlign {

    protected String class1URI;
    protected String class2URI;
    @XmlList
    protected List<BooleanVariables> evidence;
    protected Float score;
    protected String rangeName;
    protected Float rangeMIN;
    protected Float rangeMAX;

    /**
     * Gets the value of the class1URI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClass1URI() {
        return class1URI;
    }

    /**
     * Sets the value of the class1URI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClass1URI(String value) {
        this.class1URI = value;
    }

    /**
     * Gets the value of the class2URI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClass2URI() {
        return class2URI;
    }

    /**
     * Sets the value of the class2URI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClass2URI(String value) {
        this.class2URI = value;
    }

    /**
     * Gets the value of the evidence property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the evidence property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEvidence().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BooleanVariables }
     * 
     * 
     */
    public List<BooleanVariables> getEvidence() {
        if (evidence == null) {
            evidence = new ArrayList<BooleanVariables>();
        }
        return this.evidence;
    }

    /**
     * Gets the value of the score property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getScore() {
        return score;
    }

    /**
     * Sets the value of the score property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setScore(Float value) {
        this.score = value;
    }

    /**
     * Gets the value of the rangeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRangeName() {
        return rangeName;
    }

    /**
     * Sets the value of the rangeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRangeName(String value) {
        this.rangeName = value;
    }

    /**
     * Gets the value of the rangeMIN property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getRangeMIN() {
        return rangeMIN;
    }

    /**
     * Sets the value of the rangeMIN property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setRangeMIN(Float value) {
        this.rangeMIN = value;
    }

    /**
     * Gets the value of the rangeMAX property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getRangeMAX() {
        return rangeMAX;
    }

    /**
     * Sets the value of the rangeMAX property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setRangeMAX(Float value) {
        this.rangeMAX = value;
    }

}
