//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 04:59:33 PM BRT 
//


package uk.ac.manchester.dstoolkit.service.impl.util.importexport.ExpMatrix;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}NamespacePrefixes"/>
 *         &lt;element ref="{}ClassesAlign" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}PredicatesAlign" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "namespacePrefixes",
    "classesAlign",
    "predicatesAlign"
})
@XmlRootElement(name = "ExpMatrix")
public class ExpMatrix {

    @XmlElement(name = "NamespacePrefixes", required = true)
    protected NamespacePrefixes namespacePrefixes;
    @XmlElement(name = "ClassesAlign")
    protected List<ClassesAlign> classesAlign;
    @XmlElement(name = "PredicatesAlign")
    protected List<PredicatesAlign> predicatesAlign;

    /**
     * Gets the value of the namespacePrefixes property.
     * 
     * @return
     *     possible object is
     *     {@link NamespacePrefixes }
     *     
     */
    public NamespacePrefixes getNamespacePrefixes() {
        return namespacePrefixes;
    }

    /**
     * Sets the value of the namespacePrefixes property.
     * 
     * @param value
     *     allowed object is
     *     {@link NamespacePrefixes }
     *     
     */
    public void setNamespacePrefixes(NamespacePrefixes value) {
        this.namespacePrefixes = value;
    }

    /**
     * Gets the value of the classesAlign property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the classesAlign property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClassesAlign().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClassesAlign }
     * 
     * 
     */
    public List<ClassesAlign> getClassesAlign() {
        if (classesAlign == null) {
            classesAlign = new ArrayList<ClassesAlign>();
        }
        return this.classesAlign;
    }

    /**
     * Gets the value of the predicatesAlign property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the predicatesAlign property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPredicatesAlign().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PredicatesAlign }
     * 
     * 
     */
    public List<PredicatesAlign> getPredicatesAlign() {
        if (predicatesAlign == null) {
            predicatesAlign = new ArrayList<PredicatesAlign>();
        }
        return this.predicatesAlign;
    }

}
