//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 04:59:33 PM BRT 
//


package uk.ac.manchester.dstoolkit.service.impl.util.importexport.ExpMatrix;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.ac.manchester.dstoolkit.service.impl.util.importexport.ExpMatrix package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.ac.manchester.dstoolkit.service.impl.util.importexport.ExpMatrix
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ClassesAlign }
     * 
     */
    public ClassesAlign createClassesAlign() {
        return new ClassesAlign();
    }

    /**
     * Create an instance of {@link NamespacePrefixes }
     * 
     */
    public NamespacePrefixes createNamespacePrefixes() {
        return new NamespacePrefixes();
    }

    /**
     * Create an instance of {@link PredicatesAlign }
     * 
     */
    public PredicatesAlign createPredicatesAlign() {
        return new PredicatesAlign();
    }

    /**
     * Create an instance of {@link ExpMatrix }
     * 
     */
    public ExpMatrix createExpMatrix() {
        return new ExpMatrix();
    }

}
