//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 04:59:32 PM BRT 
//


package uk.ac.manchester.dstoolkit.service.impl.util.importexport.schematiccorrespondences;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}name"/>
 *         &lt;element ref="{}shortName"/>
 *         &lt;element ref="{}type"/>
 *         &lt;element ref="{}description" minOccurs="0"/>
 *         &lt;element ref="{}direction"/>
 *         &lt;element ref="{}Param" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Constructs1"/>
 *         &lt;element ref="{}Constructs2"/>
 *         &lt;element ref="{}Correspondence" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "shortName",
    "type",
    "description",
    "direction",
    "param",
    "constructs1",
    "constructs2",
    "correspondence"
})
@XmlRootElement(name = "Correspondence")
public class Correspondence {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String shortName;
    @XmlElement(required = true)
    protected String type;
    protected String description;
    @XmlElement(required = true)
    protected String direction;
    @XmlElement(name = "Param")
    protected List<Param> param;
    @XmlElement(name = "Constructs1", required = true)
    protected Constructs1 constructs1;
    @XmlElement(name = "Constructs2", required = true)
    protected Constructs2 constructs2;
    @XmlElement(name = "Correspondence")
    protected List<Correspondence> correspondence;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the shortName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * Sets the value of the shortName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortName(String value) {
        this.shortName = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the direction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirection() {
        return direction;
    }

    /**
     * Sets the value of the direction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirection(String value) {
        this.direction = value;
    }

    /**
     * Gets the value of the param property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the param property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParam().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Param }
     * 
     * 
     */
    public List<Param> getParam() {
        if (param == null) {
            param = new ArrayList<Param>();
        }
        return this.param;
    }

    /**
     * Gets the value of the constructs1 property.
     * 
     * @return
     *     possible object is
     *     {@link Constructs1 }
     *     
     */
    public Constructs1 getConstructs1() {
        return constructs1;
    }

    /**
     * Sets the value of the constructs1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Constructs1 }
     *     
     */
    public void setConstructs1(Constructs1 value) {
        this.constructs1 = value;
    }

    /**
     * Gets the value of the constructs2 property.
     * 
     * @return
     *     possible object is
     *     {@link Constructs2 }
     *     
     */
    public Constructs2 getConstructs2() {
        return constructs2;
    }

    /**
     * Sets the value of the constructs2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Constructs2 }
     *     
     */
    public void setConstructs2(Constructs2 value) {
        this.constructs2 = value;
    }

    /**
     * Gets the value of the correspondence property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the correspondence property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCorrespondence().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Correspondence }
     * 
     * 
     */
    public List<Correspondence> getCorrespondence() {
        if (correspondence == null) {
            correspondence = new ArrayList<Correspondence>();
        }
        return this.correspondence;
    }

}
